name: Rebuild BGFX shaders

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/osd/modules/render/bgfx/shaders/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/osd/modules/render/bgfx/shaders/**'

permissions:
  contents: read

jobs:
  rebuild:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-libc++

      - name: Prevent make from rebuilding GLSL parser source
        run: |
          touch 3rdparty/bgfx/3rdparty/glsl-optimizer/src/glsl/glcpp/glcpp-lex.c
          touch 3rdparty/bgfx/3rdparty/glsl-optimizer/src/glsl/glcpp/glcpp-parse.c
          touch 3rdparty/bgfx/3rdparty/glsl-optimizer/src/glsl/glcpp/glcpp-parse.h
          touch 3rdparty/bgfx/3rdparty/glslang/glslang/MachineIndependent/glslang_tab.cpp
          touch 3rdparty/bgfx/3rdparty/glslang/glslang/MachineIndependent/glslang_tab.cpp.h

      - name: Build
        env:
          MINGW64: "/mingw64"
        run: make shaders

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mame-bgfx-${{ github.sha }}
          path: bgfx/shaders
          if-no-files-found: error
