name: Build documentation

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'docs/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'docs/**'

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin latexmk python3-pip python3-sphinx texlive texlive-formats-extra texlive-science
          pip3 install sphinxcontrib-svg2pdfconverter

      - name: Build HTML documentation
        run: make -C docs html

      - name: Build PDF documentation
        run: make -C docs latexpdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mame-docs-${{ github.sha }}
          path: |
            docs/build/html
            docs/build/latex/MAME.pdf
          if-no-files-found: error
